### PR TITLE
Integration script between ASoC and ASE

### PR DESCRIPTION
**Pull request by coadaflorin**
Added the latest version for the cloudToPrem sync utility.
Complete readMe with set-up to follow-up.

### CODE REVIEW

**Review by cwtravis — APPROVED** [review]
looks fine

**Comment by CA54674PL** [comment]
CODE_OF_CONDUCT.md549075

**Comment by CA54674PL** [comment]
[Auto-Label Discussions for Actions Category](https://github.com/community/community/actions/workflows/actions_labeller.yml)

**Comment by CA54674PL** [comment]
https://github.com/community/community/actions/workflows/actions_labeller.yml/badge.svg?event=schedulehttps://github.com/community/community/actions/workflows/actions_labeller.yml

**Comment by CA54674PL** [comment]
Ahmed chami

**Pull request merged**
